### ISSUE TITLE
STONK-11: Backend > Dockerize Node App

### ISSUE THREAD

**Issue by JackyTea** [JackyTea/Mock-Stocks-Collaborative#12]
## Description

We want to dockerize the Node application for better portability and ease of deployment in various environments.

## Acceptance Criteria

- create a `Dockerfile`, possible implementation below from [dockerizing a node.js app example](https://nodejs.org/en/docs/guides/nodejs-docker-webapp):
```docker
FROM node:18
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
CMD [ "node", "server.js" ]
```
- create a `docker-compose.yml` in order to scale this to our possible multi-container setup later
```yaml
version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
```
- change the start command in the `package.json` to launch the app via docker-compose:
```bash
docker-compose up
```

## Checklist

- [x] I have verified that this issue is relevant to the current project scope
- [x] I have added the appropriate label to this issue
- [x] I have linked this issue to the project
- [x] I have followed the issue title pattern of `STONK-NUMBER: Domain > Issue Title`
